version: '3'
services:
  client:
    build: ./Client
    container_name: react-client
    ports:
      - '8080:8080'
    volumes:
      - ./client:/client
      - /client/node_modules
    networks:
      - mern-network
    depends_on:
      - server
    stdin_open: true
    tty: true

  server:
    build: ./Server
    container_name: node-server2

    ports:
      - '3001:3001'
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
